#Default server port
server:
  port: 8081

spring:
  #MySQL
  datasource:
    url: "jdbc:mysql://localhost:3306/doctor?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update