#Default server port
server:
  port: 8081

spring:
  #MySQL
  datasource:
    url: "jdbc:mysql://localhost:3306/doctor?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
springdoc:
  swagger-ui:
    path: "/docs"
  api-docs:
    enabled: true
    path: "/swagger-ui/doctor-api"
